apiVersion: v2
name: collate-ai-proxy
description: Helm chart for deploying the Collate AI Proxy
type: application
version: 0.1.0
appVersion: "1.11.4"

home: https://github.com/open-metadata/collate-ai-proxy-helm-chart

sources:
  - https://github.com/open-metadata/collate-ai-proxy-helm-chart

keywords:
  - collate
  - openmetadata
  - collate-ai-proxy
