name: Create release branch
run-name: Create release branch for ${{ inputs.release_branch_name }}
on:
  workflow_dispatch:
    inputs:
      release_branch_name:
        description: "Release branch name. E.g., '1.2.3'"
        required: true
permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-branch:
    name: Create release branch ${{ inputs.release_branch_name }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: main
        fetch-depth: 0
    - name: Update application version
      working-directory: charts/collate-ai-proxy
      env:
        NEW_VERSION: ${{ inputs.release_branch_name }}
      run: |
        old_version=$(cat ../../.version)
        export image_version="om-${NEW_VERSION}-cl-${NEW_VERSION}"

        # update flat version file
        echo "$NEW_VERSION" > ../../.version

        # update Helm chart version and appVersion
        yq eval -i '.version = strenv(NEW_VERSION)' Chart.yaml
        yq eval -i '.appVersion = strenv(NEW_VERSION)' Chart.yaml

        # update image tags in values.yaml
        yq eval -i '.image.tag = strenv(image_version)' values.yaml

    - name: Create pull request
      uses: peter-evans/create-pull-request@v7
      with:
        title: 'chore(release): Prepare ${{ inputs.release_branch_name }} release'
        body: |
          - Update application version to `${{ inputs.release_branch_name }}`
        branch: "release/${{ inputs.release_branch_name }}"
        commit-message: 'chore(release): Prepare Branch for release ${{ inputs.release_branch_name }}'
